// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentDateTime() {
  return window['go']['main']['App']['CurrentDateTime']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}
